import Head from 'next/head'
import Seo from './seo'
import { LayoutProps } from '@/types'

const Layout = ({ children }: LayoutProps): JSX.Element => {

  return (
    <>
      <Seo />
      <Head>
        <title>Formi Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main>
      </main>

      <footer></footer>
    </>
  )
}

export default Layout
